### ISSUE TITLE
ViewStyle overwrites tintColor, backgroundColor and alpha if set in IB

### ISSUE THREAD

**Issue by radimhalfar** [inloop/Styles#43]

**Comment by jakubpetrik** [comment]
that is intended behavior

**Comment by radimhalfar** [comment]
in fact not. because if you set the color in IB and apply no color in style - the style due to defaults automatically sets .backgroundColor(nil), thus it overwrites the value set in IB

**Comment by radimhalfar** [comment]
Ok then, I agree. However to make it more obvious I would suggest to change ViewStyle.Property to struct providing init with pre-defined properties which may be overwritten by developer using it. 
i.e - 
```swift ViewStyle.default ```
```swift final class ViewStyle {
    init(backgroundColor: UIColor?, tintColor: UIColor = .black, opacity: Float = 1, corners: ...)
} 
```
What do you think ? 🙂
